package scalan;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/** Marks annotated method or trait/class as having support for pattern matching.
  * Extractor methods will be generated by codegen for each method either annotated or
  * belonging to the annotated type.
  * Extractors can be used in rewriting rules to recognize IR nodes of MethodCall type,
  * which represents the call of the annotated method.
  */
@Target({ElementType.METHOD,ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface WithMethodCallRecognizers {
}
