// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.4.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Seq(
  "ch.qos.logback" % "logback-classic" % "1.3.0-alpha4",
  "ch.qos.logback" % "logback-core" % "1.3.0-alpha4",
  "com.google.code.findbugs" % "jsr305" % "3.0.2",
  "com.google.guava" % "guava" % "21.0",
  "com.lihaoyi" % "fastparse-utils_2.12" % "1.0.0",
  "com.lihaoyi" % "fastparse_2.12" % "1.0.0",
  "com.lihaoyi" % "sourcecode_2.12" % "0.1.4",
  "com.sun.mail" % "javax.mail" % "1.6.0",
  "com.typesafe" % "config" % "1.3.0",
  "com.typesafe.akka" % "akka-actor_2.12" % "2.4.20",
  "com.typesafe.scala-logging" % "scala-logging_2.12" % "3.9.0",
  "javax.activation" % "activation" % "1.1",
  "jline" % "jline" % "2.14.3",
  "org.bitbucket.inkytonik.dsinfo" % "dsinfo_2.12" % "0.4.0",
  "org.bitbucket.inkytonik.dsprofile" % "dsprofile_2.12" % "0.4.0",
  "org.bitbucket.inkytonik.kiama" % "kiama_2.12" % "2.1.0",
  "org.bouncycastle" % "bcprov-jdk15on" % "1.60",
  "org.rogach" % "scallop_2.12" % "2.1.1",
  "org.rudogma" % "supertagged_2.12" % "1.4",
  "org.scala-lang.modules" % "scala-java8-compat_2.12" % "0.8.0",
  "org.scorexfoundation" % "scorex-util_2.12" % "0.1.1",
  "org.scorexfoundation" % "scrypto_2.12" % "2.1.3",
  "org.slf4j" % "slf4j-api" % "1.8.0-beta1",
  "org.whispersystems" % "curve25519-java" % "0.5.0"
)
// LIBRARY_DEPENDENCIES_HASH 74569f6871ad9b61b16f417ef9bd49c83349af32
