// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.4.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Seq(
  "com.google.code.findbugs" % "jsr305" % "3.0.2",
  "com.google.guava" % "guava" % "21.0",
  "com.lihaoyi" % "fastparse-utils_2.12" % "1.0.0",
  "com.lihaoyi" % "fastparse_2.12" % "1.0.0",
  "com.lihaoyi" % "sourcecode_2.12" % "0.1.4",
  "com.typesafe" % "config" % "1.3.0",
  "com.typesafe.akka" % "akka-actor_2.12" % "2.4.20",
  "jline" % "jline" % "2.14.3",
  "org.bitbucket.inkytonik.dsinfo" % "dsinfo_2.12" % "0.4.0",
  "org.bitbucket.inkytonik.dsprofile" % "dsprofile_2.12" % "0.4.0",
  "org.bitbucket.inkytonik.kiama" % "kiama_2.12" % "2.1.0",
  "org.bouncycastle" % "bcprov-jdk15on" % "1.59",
  "org.rogach" % "scallop_2.12" % "2.1.1",
  "org.rudogma" % "supertagged_2.12" % "1.4",
  "org.scala-lang.modules" % "scala-java8-compat_2.12" % "0.8.0",
  "org.scorexfoundation" % "scrypto_2.12" % "2.1.1",
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "org.whispersystems" % "curve25519-java" % "0.4.1"
)
// LIBRARY_DEPENDENCIES_HASH 2fd6050330c4965e1898f7ceface99a5a6284cff
