// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.4.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Seq(
  "ch.qos.logback" % "logback-classic" % "1.1.7",
  "ch.qos.logback" % "logback-core" % "1.1.7",
  "com.github.kxbmap" % "configs_2.12" % "0.4.4",
  "com.trueaccord.lenses" % "lenses_2.12" % "0.4.12",
  "com.typesafe" % "config" % "1.3.1",
  "com.typesafe.scala-logging" % "scala-logging_2.12" % "3.9.0",
  "commons-io" % "commons-io" % "2.5",
  "io.github.scalan" % "common_2.12" % "master-4e1b2bdb-SNAPSHOT",
  "io.github.scalan" % "library-api_2.12" % "master-4e1b2bdb-SNAPSHOT",
  "io.github.scalan" % "library-conf_2.12" % "master-4e1b2bdb-SNAPSHOT",
  "io.github.scalan" % "library-impl_2.12" % "master-4e1b2bdb-SNAPSHOT",
  "io.github.scalan" % "meta_2.12" % "master-4e1b2bdb-SNAPSHOT",
  "io.github.scalan" % "plugin_2.12" % "master-4e1b2bdb-SNAPSHOT",
  "org.scala-lang.modules" % "scala-xml_2.12" % "1.0.6",
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "org.spire-math" % "debox_2.12" % "0.8.0",
  "org.typelevel" % "algebra_2.12" % "0.7.0",
  "org.typelevel" % "cats-kernel_2.12" % "0.9.0",
  "org.typelevel" % "machinist_2.12" % "0.6.1",
  "org.typelevel" % "macro-compat_2.12" % "1.1.1",
  "org.typelevel" % "spire-macros_2.12" % "0.14.1",
  "org.typelevel" % "spire_2.12" % "0.14.1"
)
// LIBRARY_DEPENDENCIES_HASH 7f42f8f62647c523bdc600f21001dacccc030b82
